SECRET_KEY = '58344a8c-1b9f-44ba-85d6-417e6a97968b'
SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://root:mysql@localhost/exam'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True
PROCESSING_STATUS_ID = 1
ACCEPTED_STATUS_ID = 2
DECLINED_STATUS_ID = 3
